### ISSUE TITLE
Cambiar el título a la página y arreglar README

### ISSUE THREAD

**Issue by Sleepy-gogo** [EBN10/Organizar-App#2]
El título seteado en la página, es el default de Vite. Esto puede ser feo y no quedar bien en un portfolio:

![imagen](https://github.com/EBN10/Organizar-App/assets/62667318/0d0fa35a-fcdc-4fcd-ad53-3f2fbd5f3977)

Se debería también cambiar el favicon de la página para que no sea el logo de Vite, antes del deploy.

Por último, se debería actualizar el **README.md** para reflejar mejor las intenciones del proyecto, en lugar de dejar el generado automáticamente por Vite.

![imagen](https://github.com/EBN10/Organizar-App/assets/62667318/255e9b8d-43c3-4418-b6b3-0ff877c0d166)

**Comment by EBN10** [comment]
Cambios aplicados
